<article class="reality level1" show="0" maxLevel="3">
	<h1>A Skewed Reality</h1>
	<h3>Local Reality</h3>
	<p>Alfredo Jaar’s the sound of silence is an installation that dedicates 300 cubic meters and 8 minutes of time to one image. This image, made by Kevin Carter, has put the famine in Rwanda on the headlines of the world’s papers. He wants to tell the story behind the image, the story that is not covered by the media. To give perspective on how our journalistic system works. Jaar is trying to show the context around the creation of this image and what side of the story got all of the coverage and what side did not get any attention at all. In his work, Alfredo Jaar often challenges the viewer to look differently at the way the media presents the world. The same is true for The Sound Of Silence, in which Alfredo Jaar wants you to think about how we as a society look at the african continent and it’s inhabitants. </p>
	<p>One of the things that triggered my interest in the work is how it tries to show the difference in reality that we experience when seeing this shocking photograph in comparison to what the actual reality is which led to the creation of this image. Where does this difference come from? How is it that images lead us to believe things that might not be true?</p>

	<h3>Orientalism</h3>
	<p>To start our search in where our reality comes from, we have to go back to the early days of colonialism. In On Orientalism, Edward Said explains why we look at the East the way we do.</p>
	<p>It all started when early western society first came into contact with the exotic cultures in the East. Because these cultures where so drastically different from ours, to try and understand them the science of Orientalism was established. </p>
	<p>Orientalism is the study of the orient by the western culture. Because of our technical and cultural advantage, we saw the Orient as our younger brother who we needed to protect and help to grow independent. This idea justified colonisation for the european countries, as we believed it was our duty to civilise the uncivilised parts of the world. </p>
	<p>On the other hand, western civilisation used the orient to define itself. Using the concept of them and us, a view of the East as an uncivilised and underdeveloped part of the world, our self-image as a superior race developed by specifying everything that we weren't as something the orient was. Edward Said explained this phenomenon: “On the one hand there are Westerners, and on the other there are Arab-Orientals; the former are (in no particular order) rational, peaceful, liberal, logical, capable of holding real values, without natural suspicion; the latter are none of these things”</p>
	<p>Centuries later, these same values and beliefs still hold. A lot has changed, colonialism has almost disappeared, most of the colonised countries are now independent states. But we still look the same way towards the Orient. A subconscious thought of terrorism every time we hear the word Islam is not uncommon. Africa is still associated with death and disease. Why do these ideas of western superiority and dominance still persist in our modern day?</p>

	<h3>A limited scope</h3>
	<p>First we have to look at how the orient is covered in our media. David Natharius wrote about our media in the general sense in his article about the dominance of the visual image in the media. We have moved from a linear and written literacy to visual and holistic literacy. This change is clearly visible in his example of our reaction on the terrorist attack on the world trade centre.  “On September 11, 2001, we were ushered into a world of terrible visual immediacy. For days after this tragedy, we were exposed, over and over again, to televised images of the planes crashing into the towers, the towers burning, and then the towers collapsing. I was in my car going to school and heard the news on the radio. My first act, on reaching the office, was to turn on the television and then phone my wife to turn on the television. Drivers on freeways looked for the first off-ramp to find a restaurant or service station or motel office that had a television set. If we had any doubt about the power of the visual image on civilisation, that doubt was forever erased. We have moved from a world of literacy to a world of visuality. And as media literacy students and scholars, it is this new world of visuality that offers us our greatest arena of exploration.” Although this example is not necessarily about the orient, it perfectly illustrates how dependent we have become on visual media to create our own reality.</p>
	<p>In Aesthetic Journalism Alfredo Cramerotti mentions three thinkers that explain why in our current culture, the dominant fiction is created through visual imagery. We see visual imagery often as truth because we assume that our visual perception is the most accurate of our senses. But we forget that we have been taught to see, just like we have been taught to read and write. This means that the reality that we construct from our visually dominated media feels more real than written media would, but actually is just as inaccurate. In the sound of silence this inaccuracy is conceptualised by showing that there is more context behind Kevin Carter’s picture than what is visible. A lot of what we get out of the photograph is based on our pre-existing knowledge about the Orient, and in this case Africa. We do this to fill in the blanks that the photograph cannot show us. Because we miss a lot of information about the context, people got angry at Carter for not helping the girl, when Jaar fills in the blanks as to why Carter didn’t help the little girl, we might suddenly understand the situation and agree with Carter’s decision.</p>
	<h3>The Feedback Loop</h3>
	<p>Because of this inaccuracy in reporting we subconsciously see our own beliefs and interpretations as truths. Effectively creating a feedback system in which the preconceived notions about the orient are constantly reinforced by the images that we see about it.</p>
	<p>But the inaccuracy in visual media is not the only reason our knowledge about the orient has stayed so limited. Storytelling is another large component of journalism. Journalists use it all the time to put the news into logical and manageable chunks. The problem with this approach is that everything that doesn't fit into a simple narrative either does not make it in to the news or when it does it is mostly ignored. John Green exemplifies this by comparing it to our desire for stories to have a hero and a villain. “We do allow a little bit of grey on both sides but most stories have to be black and white to make it into the dominant fiction.” Our view of the orient as an inferior still holds after all this time because the stories that challenge this view often do not fit into a simple narrative. Of course our own story does not fit into this narrative either, but because it is much closer to us and less mediated the same inaccuracies do not occur.</p>

	<h3>How to break the loop</h3>
	<p>The sound of silence and other works from Alfredo Jaar, effectively show how Aesthetic Journalism can be used to try and challenge our perception of the orient. They try to overcome the limitations created by journalism by showing the systems that create them. </p>
	<br>
	<br>
	<i>Literatuurlijst</i>
	<ul>
		<li>Cramerotti - Aesthetic Journalism</li>
		<li>Edward Said - On Orientalism</li>
		<li>Ahmad Murad Merican - Orientalism in reporting religion</li>
	</ul>
</article>