<article class="reality" show="1" maxLevel="3">
	<span class="reality level1">
		<h1 class="reality level3">A <span class="reality level2">Skewed</span> Reality</h1>
			<h3 class="reality level3">Local Reality</h3>
			<p><span class="reality level3">Alfredo Jaar</span>’s the sound of silence is an installation that dedicates 300 cubic meters and 8 minutes of time to <span class="reality level3">one image. This image</span>, made by Kevin Carter, has put the <span class="reality level3">famine</span> in <span class="reality level3">Rwanda</span> on the <span class="reality level3">headlines of the world</span>’s papers. He wants to tell the story behind the image, <span class="reality level3">the story that is</span> not <span class="reality level3">covered by the media</span>. To give perspective on how our journalistic system works. Jaar is trying to show <span class="reality level3">the context</span> around the creation of this image and what <span class="reality level3">side of the story</span> got all of the <span class="reality level3">coverage</span> and what side did not get any <span class="reality level3">attention</span> at all. In his work, Alfredo Jaar often <span class="reality level3">challenges the viewer</span> to look <span class="reality level3">differently</span> at the way the <span class="reality level3">media</span> presents the world. The same is true for <span class="reality level3">The Sound Of Silence</span>, in which Alfredo Jaar wants you to think about how we as a society <span class="reality level3">look at the african continent</span> and it’s inhabitants. </p>
			<p>One of the things that triggered my interest in the work is how it tries to show <span class="reality level3">the difference in</span> reality that we <span class="reality level3">experience</span> when seeing this shocking photograph <span class="reality level3">in comparison to</span> what the actual reality is which led to the creation of <span class="reality level3">this image.</span> Where does this difference come from? How is it that images lead us to believe things that might not <span class="reality level3">be true?</span></p>
		
			<h3 class="reality level3">Orientalism</h3>
			<p>To start our <span class="reality level3">search</span> in where our reality comes from, we have to go back to the early days of <span class="reality level3">colonialism.</span> In On <span class="reality level3">Orientalism</span>, Edward Said <span class="reality level3">explains</span> why we look at <span class="reality level3">the East</span> the way we do.</p>
			<p>It all started <span class="reality level3">when</span> early <span class="reality level3">western society</span> first <span class="reality level3">came into contact with</span> the exotic cultures in <span class="reality level3">the East.</span> Because these cultures where so drastically different from ours, to try and understand them the science of Orientalism was established. </p>
			<p><span class="reality level3">Orientalism is</span> the study of the orient by the western culture. Because of <span class="reality level3">our</span> technical and cultural advantage, we saw the <span class="reality level3">Orient</span> as our younger brother who we needed to protect and <span class="reality level3">help to grow</span> independent. This idea justified colonisation for the european countries, as we believed <span class="reality level3">it was our duty to civilise</span> the uncivilised parts of <span class="reality level3">the world.</span> </p>
			<p>On the other hand, <span class="reality level3">western civilisation</span> used the orient to <span class="reality level3">define itself.</span> Using the concept of them and us, a view of <span class="reality level3">the East</span> as an <span class="reality level3">uncivilised</span> and underdeveloped <span class="reality level3">part of the world</span>, our <span class="reality level3">self-image</span> as a <span class="reality level3">superior</span> race developed by specifying everything that we weren't as something the orient was. Edward Said explained this phenomenon: “On the one hand there are Westerners, and on the other there are Arab-Orientals; the former are (in no particular order) <span class="reality level3">rational, peaceful, liberal, logical, capable of holding real values, without natural suspicion</span>; the latter are <span class="reality level3">none of these things</span>”</p>
			<p>Centuries later, these same values and beliefs still hold. A lot has <span class="reality level3">changed</span>, colonialism has almost disappeared, most of the <span class="reality level3">colonised countries</span> are <span class="reality level3">now independent states.</span> But we still look the same way towards the Orient. A subconscious thought of <span class="reality level3">terrorism</span> every time we hear the word Islam is not uncommon. Africa is still associated with <span class="reality level3">death and disease.</span> Why do these ideas of western superiority and dominance still <span class="reality level3">persist in our modern day?</span></p>
		
			<h3 class="reality level3">A limited scope</h3>
			<p>First we have to look at how the orient is covered in our <span class="reality level3">media.</span> David <span class="reality level3">Natharius wrote about</span> our media in the general sense in his article about the dominance of the visual image in the <span class="reality level3">media.</span> We have moved from a <span class="reality level3">linear</span> and <span class="reality level3">written</span> literacy <span class="reality level3">to visual</span> and <span class="reality level3">holistic literacy.</span> This change is clearly visible in his example of our reaction on the terrorist attack on the <span class="reality level3">world trade centre.</span>  “On September 11, 2001, we were ushered into a world of terrible visual immediacy. For days after this tragedy, we were exposed, over and over again, to <span class="reality level3">televised images of the planes crashing</span> into the towers, <span class="reality level3">the towers burning</span>, and then the towers collapsing. I was in my car going to school and heard the news on the radio. My first act, on reaching the office, was to turn on the television and then phone my wife to turn on the television. Drivers on freeways looked for the first off-ramp to find a restaurant or service station or motel office that had a television set. If we had any doubt about the power of the visual image on civilisation, that doubt was forever erased. We have <span class="reality level3">moved from a world of literacy to a world of visuality.</span> And as media literacy students and scholars, it is this new world of visuality that offers us our greatest arena of exploration.” Although <span class="reality level3">this example</span> is not necessarily about <span class="reality level3">the orient, it</span> perfectly illustrates how <span class="reality level3">dependent we have become on visual</span> media to create our own <span class="reality level3">reality</span>.</p>
			<p><span class="reality level3">In Aesthetic Journalism Alfredo Cramerotti mentions</span> three thinkers that explain <span class="reality level3">why</span> in our current culture, <span class="reality level3">the dominant fiction is created through visual imagery.</span> We see visual imagery often as <span class="reality level3">truth</span> because we assume that our visual perception is <span class="reality level3">the most accurate</span> of our <span class="reality level3">senses.</span> But we <span class="reality level3">forget</span> that we <span class="reality level3">have</span> been <span class="reality level3">taught</span> to see, just like we have been taught to <span class="reality level3">read</span> and <span class="reality level3">write.</span> This means that the reality that we <span class="reality level3">construct</span> from our <span class="reality level3">visually dominated media</span> feels more <span class="reality level3">real</span> than written media would, but actually is just as <span class="reality level3">inaccurate.</span> In the sound of silence this inaccuracy is <span class="reality level3">conceptualised by showing</span> that there is more <span class="reality level3">context behind</span> Kevin Carter’s <span class="reality level3">picture</span> than what is visible. A lot of what we get out of the photograph is <span class="reality level3">based on our pre-existing knowledge</span> about the Orient, and in this case <span class="reality level3">Africa.</span> We do this to fill in <span class="reality level3">the blanks</span> that the photograph <span class="reality level3">cannot show</span> us. Because we <span class="reality level3">miss</span> a lot of information about the context, people got angry at Carter for not helping the girl, when Jaar fills in the blanks as to why Carter didn’t help the little girl, <span class="reality level3">we might</span> suddenly understand the situation and <span class="reality level3">agree with Carter’s decision.</span></p>
			<h3>The Feedback Loop</h3>
			<p>Because of this inaccuracy in reporting <span class="reality level3">we subconsciously see</span> our own beliefs and interpretations <span class="reality level3">as truths.</span> Effectively creating <span class="reality level3">a feedback system</span> in which the preconceived notions about the orient are constantly <span class="reality level3">reinforced by</span> the <span class="reality level3">images that we see</span> about it.</p>
			<p>But the inaccuracy in visual media is not the only <span class="reality level3">reason our knowledge about the orient</span> has stayed so <span class="reality level3">limited. Storytelling is</span> another <span class="reality level3">large component of</span> journalism. Journalists use it all the time to put the news into <span class="reality level3">logical and manageable chunks. </span>The problem with this approach is that <span class="reality level3">everything</span> that doesn't fit into a simple narrative either does not make it in to the news or when it does it is <span class="reality level3">mostly ignored.</span> John Green exemplifies this <span class="reality level3">by comparing</span> it to our desire for stories to have <span class="reality level3">a hero and a villain. “We</span> do <span class="reality level3">allow a little bit of grey</span> on both sides but most stories have to be black and white <span class="reality level3">to make it into the dominant fiction.”</span> Our view of the orient as an inferior still holds after all this time because <span class="reality level3">the stories that challenge this view</span> often do not fit into a simple narrative. Of course our own story does not fit into this narrative either, but because it <span class="reality level3">is much closer to us</span> and less mediated the same inaccuracies <span class="reality level3">do not occur.</span></p>
		
			<h3 class="reality level3">How to break the loop</h3>
			<p>The sound of silence and other works from Alfredo Jaar, effectively show how Aesthetic Journalism can be used to try and challenge our perception of the orient. They try to overcome the limitations created by journalism by showing the systems that create them. </p>
			<span class="reality level3">
				<i>Literatuurlijst</i>
				<ul>
					<li>Cramerotti - Aesthetic Journalism</li>
					<li>Edward Said - On Orientalism</li>
					<li>Ahmad Murad Merican - Orientalism in reporting religion</li>
				</ul>
			</span>
		</span>
</article>